name: Generate Game of Life

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jstrieb/github-readme-life@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: Cruz-Arthur

      - run: git config user.name "Cruz-Arthur" && git config user.email "arthurcaue100@gmail.com"

      - run: |
          git add -A
          git diff --cached --quiet || git commit -m "chore: update game of life"
          git push
